version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/mern-backend
    container_name: mern-backend
    restart: always
    environment:
      - MONGO_URI=${{ secrets.MONGO_URI }}
    networks:
      - mern-network
    ports:
      - "5000:5000"

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/mern-frontend
    container_name: mern-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - mern-network
    ports:
      - "80:80"

networks:
  mern-network:
    driver: bridge
