name: Deploy MERN App to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend ./devops_frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend ./devops_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 & Deploy Containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend

            docker stop mern-frontend mern-backend || true
            docker rm mern-frontend mern-backend || true

            docker run -d -p 5000:5000 --name mern-backend \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              ${{ secrets.DOCKER_USERNAME }}/mern-backend

            docker run -d -p 80:80 --name mern-frontend ${{ secrets.DOCKER_USERNAME }}/mern-frontend
