name: Deploy MERN App to AWS

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install and Build Frontend
      - name: Install & Build Frontend
        run: |
          cd devops_frontend
          npm install
          npm run build

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd devops_backend
          npm install

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build & Push Docker Images
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend ./devops_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend ./devops_frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/mern-deployment/"

      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Stop and remove existing containers
            docker stop mern-frontend mern-backend || true
            docker rm mern-frontend mern-backend || true

            # Pull latest images
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend

            # Create Docker network if not exists
            docker network create mern-network || true

            # Run backend
            docker run -d --name mern-backend --network mern-network -p 5000:5000 \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              ${{ secrets.DOCKER_USERNAME }}/mern-backend

            # Run frontend
            docker run -d --name mern-frontend --network mern-network -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/mern-frontend
